#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/techno-tim/littlelink-server
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [littlelink-server documentation](https://github.com/techno-tim/littlelink-server).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  META_TITLE: Ilyas Sakhanov
  META_DESCRIPTION: Ilyas Sakhanov page
  META_AUTHOR: Ilyas Sakhanov
  THEME: Dark
  FAVICON_URL: https://media.licdn.com/dms/image/v2/D4D03AQGx0EZpmNP1sA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1731778298983?e=1756339200&v=beta&t=lbGtsJITCvWYF264DLe85UlZpDr6vjpmWDqcJfvleuM 
  AVATAR_URL: https://media.licdn.com/dms/image/v2/D4D03AQGx0EZpmNP1sA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1731778298983?e=1756339200&v=beta&t=lbGtsJITCvWYF264DLe85UlZpDr6vjpmWDqcJfvleuM
  AVATAR_2X_URL: https://media.licdn.com/dms/image/v2/D4D03AQGx0EZpmNP1sA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1731778298983?e=1756339200&v=beta&t=lbGtsJITCvWYF264DLe85UlZpDr6vjpmWDqcJfvleuM 
  AVATAR_ALT: Ilyas Sakhanov Profile Pic
  NAME: Ilyas Sakhanov
  BIO: Hey! Just a place where you can connect with me!
  GITHUB: https://github.com/ilyassakhanov
  # TWITTER: https://twitter.com/TechnoTimLive
  # INSTAGRAM: https://www.instagram.com/techno.tim
  # YOUTUBE: https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A
  # TWITCH: https://www.twitch.tv/technotim/
  # DISCORD: https://discord.gg/DJKexrJ
  # TIKTOK: https://www.tiktok.com/@technotim
  # KIT: https://kit.co/TechnoTim
  # FACEBOOK: https://facebook.com
  # FACEBOOK_MESSENGER: https://facebook.com
  # LINKED_IN: https://linkedin.com
  # PRODUCT_HUNT: https://www.producthunt.com/
  # SNAPCHAT: https://www.snapchat.com/
  # SPOTIFY: https://www.spotify.com/
  # REDDIT: https://www.reddit.com/
  # MEDIUM: https://medium.com
  # PINTEREST: https://www.pinterest.com/
  # EMAIL: you@example.com
  # EMAIL_ALT: you@example.com
  # SOUND_CLOUD: https://souncloud.com
  # FIGMA: https://figma.com
  # TELEGRAM: https://telegram.org/
  # TUMBLR: https://www.tumblr.com/
  # STEAM: https://steamcommunity.com/
  # VIMEO: https://vimeo.com/
  # WORDPRESS: https://wordpress.com/
  # GOODREADS: https://www.goodreads.com/
  # SKOOB: https://www.skoob.com.br/
  FOOTER: Thanks for stopping by!

#  -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
